name: Shell CI

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.sh'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.sh'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: |
          find . -type f -name "*.sh" -exec shellcheck {} +